# Generated by Django 4.1.1 on 2022-11-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
