# Generated by Django 4.1.1 on 2022-11-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_orderitem_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.shelf'),
        ),
    ]
